### ISSUE TITLE
Improvements to Django content

### ISSUE THREAD

**Issue by rasoolsomji** [getfutureproof/fp_guides_wiki#1]
I have a few suggestions for the Django content here (https://github.com/getfutureproof/fp_guides_wiki/wiki/Django). Github doesn't allow you to make PRs for wikis otherwise I would have made and proposed changes that way

- View functions' first argument is conventionally `request` rather than `req`

- `render()` conventionally takes `(request, <template name>, context)` as its arguments, where context is a dictionary.  In your `register()` function it instead uses `data`

- For `class Dog`, the field `breed`, needs `null=True` for `on_delete=models.SET_NULL` to be valid

- In the 'User registration & authentication' section, there is a typo with UserSignupFormm having an extra m

- In the 'Protecting routes' section, the `profile()` function won't work. It should be `req.user.username` (which really should be `request.user.username` according to my first bullet point)

**Comment by Gingertonic** [comment]
Thank you for your comments @rasoolsomji, we'll fix up the typos and things that got lost!

We like to bring up conventions in our live lectures but give examples that use alternatives - for beginners it can be easy to attach 'magic' to certain parameter and variable names so we like to make it clear that no magic is involved, just consistency!
