### ISSUE TITLE
Syntax Error: Script Closing Tag missing /

### ISSUE THREAD

**Issue by xargon666** [getfutureproof/fp_guides_wiki#11]
```
<!-- in index.html -->
<script defer src="bundle.js"><script>
<!-- Update bundle location as required -->
```

**Comment by rom-30** [comment]
Hi @xargon666 can you please share the url of the page? It will make it easier to amend things :)

**Comment by xargon666** [comment]
Took me a while to track it down again! :D
https://github.com/getfutureproof/fp_guides_wiki/wiki/Simple-Client-Side-Dev-Server

**Comment by rom-30** [comment]
Sorted - Thanks for flagging
