### ISSUE TITLE
Unable to clone repo locally

### ISSUE THREAD

**Issue by xargon666** [getfutureproof/fp_guides_wiki#13]
```
$ git clone https://github.com/getfutureproof/fp_guides_wiki.wiki.git
Cloning into 'fp_guides_wiki.wiki'...
remote: Enumerating objects: 1715, done.
remote: Total 1715 (delta 0), reused 0 (delta 0), pack-reused 1715
Receiving objects: 100% (1715/1715), 440.22 KiB | 4.40 MiB/s, done.
Resolving deltas: 100% (1093/1093), done.
error: invalid path 'Testing-React:-Jest-and-Enzyme.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by rom-30** [comment]
To clone a wiki, you need to prepend the word `git` with `wiki` @xargon666 :) 
Try this 👇 
`git clone git@github.com:getfutureproof/fp_guides_wiki.wiki.git`

**Comment by xargon666** [comment]
hmmm it still doesn't work for me 
I thought I would be able to clone the entire wiki collection, but all I can the first README page with this:
`git clone git@github.com:getfutureproof/fp_guides_wiki.git`

does this line suggest there is an issue with a path?
`error: invalid path 'Testing-React:-Jest-and-Enzyme.md'`
