### ISSUE TITLE
Broken link for the Socket.io Cheatsheet

### ISSUE THREAD

**Issue by buscaroli** [getfutureproof/fp_guides_wiki#17]
Futureproof wiki - Intro to Socket.IO.
The link to the socket.io cheatsheet is broken. 
Please consider updating it to the new version located at:

V3 ->  https://socket.io/docs/v3/emit-cheatsheet/

V4 -> https://socket.io/docs/v4/emitting-events/

**Comment by rom-30** [comment]
The link has been updated to https://socket.io/docs/v4/emitting-events/
thanks for flagging :)
