### ISSUE TITLE
Wrong weeks assigned to laps 

### ISSUE THREAD

**Issue by devSamC** [getfutureproof/fp_guides_wiki#2]
Lap 2 assigned weeks 8-10, while lap 3 assigned 5-7. 

![Screenshot_20210903-133639](https://user-images.githubusercontent.com/44700232/132006403-9a431cf3-f7de-4678-9a2f-664df7bd1b77.jpg)

**Comment by rom-30** [comment]
Thank you @devSamC  - Changes have been made
