### ISSUE TITLE
Logic-in-JavaScript.md bug

### ISSUE THREAD

**Issue by mklilley** [getfutureproof/fp_guides_wiki#5]
I think I found a little bug in the code of the `reduce` section on the wiki page `Logic in JavaScript` on `Lap 1`.

The semi-colon inside the reduce function below causes the code to produce an error:

```
const prices = [2.99, 4.75, 5.00, 12.99];
prices.reduce((runningTotal, nextValue); => runningTotal + nextValue) 
``` 

I've attached the markdown file which fixes the problem.
[Logic-in-JavaScript.md](https://github.com/getfutureproof/fp_guides_wiki/files/8231842/Logic-in-JavaScript.md)

I would have done a PR but couldn't find a way to do this easily on a wiki repo.

**Comment by rom-30** [comment]
Thanks for flagging - The code has been modified
