### ISSUE TITLE
Add a + (plus) character to the WarmUP Week Section

### ISSUE THREAD

**Issue by buscaroli** [getfutureproof/fp_guides_wiki#8]
WarmUP Week - Section 'Just Enough Javascript'.
Please consider adding a + (plus) sign to the first row of the "Some Essential Operators" Table

**Comment by rom-30** [comment]
Fixed
![image](https://user-images.githubusercontent.com/48137278/167428373-73c8289d-7ba0-4be1-96c4-2eea0f819e9a.png)
Thanks for letting us know
